### ISSUE TITLE
Uhm...I found out why the HomeKit plugin isn't working anymore!

### ISSUE THREAD

**Issue by atchoo78** [telldus/tellstick-server-homekit#1]
@mickeprag : I managed to track debug and pinpoint the exact reason why the HomeKit plugin is kind of sketchy and often not working. I'll try to to write it step by step:

The first clue I found was this error message when trying to install it on tellstick-server locally:

```python

ERROR:root:No module named pybonjour
ERROR:root:('/Users/andreas/tellstick-server/plugins/tellstick-server-homekit/src/homekit/HomeKit.py', 22, '<module>', 'from .Bonjour import Bonjour')
ERROR:root:('/Users/andreas/tellstick-server/plugins/tellstick-server-homekit/src/homekit/Bonjour.py', 7, '<module>', 'import pybonjour')
```

So I extracted [pybonjour-1.1.1.tar.gz](https://github.com/telldus/tellstick-server-homekit/blob/master/pybonjour-1.1.1.tar.gz) and installed it locally from setup.py, to see which files it copied where:

```python

python setup.py install

```

Got the following output:

```python

running install
running build
running build_py
running install_lib
running install_egg_info
Writing /Library/Python/2.7/site-packages/pybonjour-1.1.1-py2.7.egg-info
Copying pybonjour.py to /Library/Python/2.7/site-packages/pybonjour.py

```
...and something about byte-compiling the *.pyc file. I haven't been able to recreate that message, but it's not important.

So I cd'd into `/Library/Python/2.7/site-packages` and copied the mentioned files:

- pybonjour-1.1.1-py2.7.egg-info
- pybonjour.py
- pybonjour.pyc

into `~/tellstick-server/build/env/lib/python2.7/site-packages/`, then

```bash

./tellstick.sh run

```

Lo and behold, it actually worked!  🤯

So I narrowed it down to an error with the last line of text in your [requirements.txt](https://github.com/telldus/tellstick-server-homekit/blob/master/requirements.txt):

```python

file:../tellstick-server-homekit/pybonjour-1.1.1.tar.gz#egg=pybonjour

```
I'm guessing either the absolute path or in the reference to the egg itself. 

Now there's only one thing I need to find out:
Where is the "site-packages" location on the actual Tellstick, so I can "hotfix" it? 

🥳

Best regards,

Andreas

**Comment by atchoo78** [comment]
> Now there's only one thing I need to find out:
Where is the "site-packages" location on the actual Tellstick, so I can "hotfix" it?

Nevermind, I found it.

A.

**Comment by atchoo78** [comment]
I'm starting to think the rabbit hole is a bit deeper than I first thought, but I honestly don't know.

**Comment by atchoo78** [comment]
Ka-Pow!

![IMG_2262](https://user-images.githubusercontent.com/20549049/75065813-e25bc680-54e9-11ea-8fbe-772b1515519c.png)
![IMG_2261](https://user-images.githubusercontent.com/20549049/75065815-e38cf380-54e9-11ea-8d35-d6af6621337e.png)

**Comment by mickeprag** [comment]
As you have figured the issue is not in pybonjour but deeper. For anyone coming here in the future here is some information. 

When pairing with an iPhone all authentication steps is performed and TellStick thinks it was a success but the iPhone displays an error message. This problem is that the iPhone gives not information about the issue.

There exists a helper tool from Apple that's can be used to diagnose the issue (called HAT). Using this tools gives no error and the authentication is successful.

**Comment by atchoo78** [comment]
Are you sure that HAT is the title? I can't find it anywhere in the Apple dev site. Thanks.

**Comment by mickeprag** [comment]
Yes, its called HomeKit accessory tester (HAT) but is only available to mfi members under NDA :(
